{% set version = "3.3.2" %}

package:
  name: libarchive
  version: {{ version }}

source:
  fn: libarchive-{{ version }}.tar.gz
  url: https://github.com/libarchive/libarchive/archive/v{{ version }}.tar.gz
  sha256: 22560b89d420b11a4a724877bc6672b7d7c0f239e77d42a39dcc5a9c3b28db82
  patches:
    - 0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
    - 0002-xar-fix-bad-seek-in-move_reading_point.patch
    - 0003-VC9-compatibility-test-for-BCryptDeriveKeyPBKDF2.patch
    - 0004-VC9-compatibility-define-BCRYPT_SUCCESS.patch
    # This should not be applied in general. It exists so I can build it for
    # debugging Visual Studio where warnings are errors for some reason.
    # Hiding warnings is poor practice.
    # - 0005-VC9-compatibility-ignore-some-warnings.patch
    - 0006-VC-openssl-define-inline-as-__inline.patch
    # These warnings are errors when compiling lz-4 support
    - 0007-CMake-VC9-compatibility-ignore-some-warnings.patch
    - 0008-VC9-compatibility-remove-C99.patch

build:
  number: 5

requirements:
  build:
    - {{ compiler('c') }}
    - c99-to-c89          # [win and vc<14]
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - pkg-config  # [unix]
    - cmake  # [win]
  host:
    - bzip2
    - libiconv  # [osx]
    - lz4-c
    - xz
    - lzo
    - openssl
    - libxml2
    - zlib

test:
  files:
    - test/hello_world.xar
  commands:
    # Verify pkg-config file is in place.
    - test -f "${PREFIX}/lib/pkgconfig/libarchive.pc"  # [unix]

    # Verify headers are in place.
    - test -f "${PREFIX}/include/archive.h"            # [unix]
    - test -f "${PREFIX}/include/archive_entry.h"      # [unix]

    # Verify libraries are in place.
    - test -f "${PREFIX}/lib/libarchive.a"             # [unix]
    - test -f "${PREFIX}/lib/libarchive.so"            # [linux]
    - test -f "${PREFIX}/lib/libarchive.dylib"         # [osx]

    # Check for commands
    - bsdcat --version
    - bsdcpio --version
    - bsdtar --version
    - bsdtar -tf test/hello_world.xar

about:
  home: http://www.libarchive.org/
  summary: Multi-format archive and compression library
  license: BSD 2-Clause

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
