{% set version = "3.3.3" %}

package:
  name: libarchive
  version: {{ version }}

source:
  fn: libarchive-{{ version }}.tar.gz
  url: https://github.com/libarchive/libarchive/archive/v{{ version }}.tar.gz
  sha256: 720da414e7aebb255fcdaee106894e4d30e2472ac1390c2c15b70c84c7479658

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - pkg-config  # [unix]
    - {{ compiler('c') }}
  host:
    - bzip2
    - expat
    - libiconv
    - openssl
    - xz
    - zlib

  run:
    - bzip2
    - expat
    - libiconv
    - openssl
    - xz
    - zlib

test:
  commands:
    # Verify pkg-config file is in place.
    - test -f "${PREFIX}/lib/pkgconfig/libarchive.pc"  # [unix]

    # Verify headers are in place.
    - test -f "${PREFIX}/include/archive.h"            # [unix]
    - test -f "${PREFIX}/include/archive_entry.h"      # [unix]

    # Verify libraries are in place.
    - test -f "${PREFIX}/lib/libarchive.a"             # [unix]
    - test -f "${PREFIX}/lib/libarchive${SHLIB_EXT}"   # [unix]

    # Check for commands
    - bsdcat --version
    - bsdcpio --version
    - bsdtar --version

about:
  home: http://www.libarchive.org/
  summary: Multi-format archive and compression library
  license: BSD 2-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
