# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "reWJSUc12wFRirnmIPgEyDX1jifDWZY5t1zaiVv0/Jot9KxzsYQ8J5H8SgL7lz5rQk6UGWOUy7RC2m0wT6VbOGJQ/liRnP4UKEy3O7MGt2ObIJMrgDlAvpkD9eAwwCNVKK1PSMK9yfTBc7dh1ByJ6B+pVaCXhya2HvZx/au021yoQ/lBnIh8TIJTeCm0FrpCZhxnYhDDa0PfA1OArQs+PbMShjMn60gK6INbRYSwx7sGpzRgfQrbswickSLR+5CempmTWNZU6/Tb+hsoPLZp7J0JNcD9a38hnXxGScK0frbh/oA/ozhz34durl3CBKB3LO0xMn2AZr97XBHjQcl8GGMBC9QdzbP1J8GgAz0KG2dbznEbxpqlk/AUhVA86OaV1exzLDtTy6FHJC2mEjji3dklmstOdHlRcsQeI5Kl8Z5zmy6MOPSri2o7RnyLr/PT4uOgkwLMwF98YfY8zTp6CfE+13lT7x4mC4CyinW4WGUdkbrCUuUTm4p6wTgxYWwUyhSZKuW/j0WB3OeAlwOXRvtXc0/Hht7frdf/lB9CBFVkhmXoerjy5XsdB8aDIswmUIArh2Mr6Qz3cXyzgzOXfEKNrPiNopj6p3RMq1DSHhFSzY+cU60//E40Rrn9wvUJDbzUPTjaYH6WVkVP5/bGB57SYhEqJra2/rMqvDJExc0="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
