travis:
  secure:
    BINSTAR_TOKEN: NLBTJ699deFVK01o18H/70OFtDTuUQ9ziqp06545xqnjh9YlrwPHZhsdIHvb1+jDERxltjEnvC00xT5QyZA2Spdgt0JXT9HSpSh3itGZZb7a6fvEQUIsKKuk1T0dCil96Z2zOxur87iRld03MG5bR8sxSMaqnmzZoDDQgOH6sRH+CuJkd2kc2a5BqD1/sLZ4Lhu48pwJC13SkXuBq//nQRS95te+BK9fa2ls1uqUAJjCH9ItLhWW8jQhyMs5BFaOrIgavKvVB7fGRwGGp2YhJ9wzgcgb/9wx2Bj1N3p16SKVAmHj5xn1+naQQSw06oHvqT+6SBs0b4HtmNyw1sgLFeADUdJswo6aMUJiF2FhO7d6EMaP0I8Z+islPzSFqvZMrcpkXhhW6hCJKVMHQCXgzp7lPctYKOSMCPonVFmebKQo65hRpd/N9GLcmCgZ7lfDKMV2s6zJt1yGfjEzb/wlF1pnallykp0xUVFdlshFSzRY5LRPJ4QQctNSWvbzHQhF4nx72jnpt0EGx61H5+cJb77RpAIZkaF4CfibNxbixnKYMXPeub5ILSfY1JaF5n7PcPS552iqaMfGPzKmQGYhwqCFQSQ4zBUO484a7XGmWbEcMjMDb+J66oLCXK2s/dRwKhAZvufzs1ZpJ5vlanc52L9ms/eHh2PjhcoRb9QdZCQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
