travis:
  secure:
    BINSTAR_TOKEN: reWJSUc12wFRirnmIPgEyDX1jifDWZY5t1zaiVv0/Jot9KxzsYQ8J5H8SgL7lz5rQk6UGWOUy7RC2m0wT6VbOGJQ/liRnP4UKEy3O7MGt2ObIJMrgDlAvpkD9eAwwCNVKK1PSMK9yfTBc7dh1ByJ6B+pVaCXhya2HvZx/au021yoQ/lBnIh8TIJTeCm0FrpCZhxnYhDDa0PfA1OArQs+PbMShjMn60gK6INbRYSwx7sGpzRgfQrbswickSLR+5CempmTWNZU6/Tb+hsoPLZp7J0JNcD9a38hnXxGScK0frbh/oA/ozhz34durl3CBKB3LO0xMn2AZr97XBHjQcl8GGMBC9QdzbP1J8GgAz0KG2dbznEbxpqlk/AUhVA86OaV1exzLDtTy6FHJC2mEjji3dklmstOdHlRcsQeI5Kl8Z5zmy6MOPSri2o7RnyLr/PT4uOgkwLMwF98YfY8zTp6CfE+13lT7x4mC4CyinW4WGUdkbrCUuUTm4p6wTgxYWwUyhSZKuW/j0WB3OeAlwOXRvtXc0/Hht7frdf/lB9CBFVkhmXoerjy5XsdB8aDIswmUIArh2Mr6Qz3cXyzgzOXfEKNrPiNopj6p3RMq1DSHhFSzY+cU60//E40Rrn9wvUJDbzUPTjaYH6WVkVP5/bGB57SYhEqJra2/rMqvDJExc0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
